language : node_js

node_js:
  - "8"
  - "10"
  - "12"

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master
  - develop

install:
 - npm install

before_script:
 - npm run build-ts

script:
 - npm test

after_script:
 - npm run coverage
